# Generated by Django 3.2.16 on 2023-01-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model1', '0002_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='voted_today',
        ),
        migrations.AddField(
            model_name='customuser',
            name='votes_left',
            field=models.IntegerField(default=5),
        ),
    ]
